"""Utility functions and dataclasses for agent operations."""

from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field
from functools import wraps
from loguru import logger

# Type aliases for Transition
Observation = Dict[str, Any]
Metrics = Dict[str, Any]


@dataclass
class TokensWithLogprobs:
    """Tokens generated by the LLM with their log probabilities."""

    token_ids: List[int]
    logprobs: Optional[List[float]] = None
    text: Optional[str] = None


@dataclass
class Observation:
    """Tokens corresponding to an observation message from the environment"""

    input_ids: List[int]


@dataclass
class Transition:
    """Records a single LLM call transition for RL training."""

    ob: Observation
    ac: TokensWithLogprobs
    reward: float
    episode_done: bool
    metrics: Metrics = field(default_factory=dict)


@dataclass
class StepResult:
    """Result of a single agent step."""

    done: bool
    finish_reason: Optional[str]
    result: Optional[Any]

    @classmethod
    def continuing(cls, result: Optional[Any] = None):
        """Create a result indicating the agent should continue."""
        return cls(done=False, finish_reason=None, result=result)

    @classmethod
    def finished(cls, reason: str, result: Optional[Any] = None):
        """Create a result indicating the agent should stop."""
        return cls(done=True, finish_reason=reason, result=result)

    def to_tuple(self):
        """Convert to tuple format for backwards compatibility."""
        return self.done, self.finish_reason, self.result


def record_transition(func):
    """Decorator to record transitions for each LLM call.

    Captures:
    - Observation: input_ids fed to LLM
    - Action: output tokens and logprobs from LLM
    - Records transition with metadata
    """

    @wraps(func)
    async def wrapper(self, *args, **kwargs):
        # Capture observation (input_ids) before LLM call
        observation = Observation(input_ids=kwargs.get("input_ids", []))

        # Call the original function (LLM generation)
        result = await func(self, *args, **kwargs)
        response_str, meta_info = result
        print(f"response_str: {response_str}")

        # Extract action information
        output_tokens = meta_info.get("output_tokens", [])
        logprobs = meta_info.get("logprobs", None)

        action = TokensWithLogprobs(
            token_ids=output_tokens,
            logprobs=logprobs,
            text=response_str,
        )

        # Create transition with default values
        # Reward and episode_done will be updated based on step outcome
        transition = Transition(
            ob=observation,
            ac=action,
            reward=0.0,  # Default, can be updated later
            episode_done=False,  # Default, can be updated later
            metrics={
                "finish_reason": meta_info.get("finish_reason"),
            },
        )

        # TODO(@csy): Add agent_id tracking to transitions
        # When tools spawn subagents that also call LLM generation, transitions from
        # different agents get mixed in self.transitions. For TITOReActAgent incremental
        # encoding, we need to identify which transitions belong to the current agent.
        # Proposed solution: Add `agent_id: Optional[str] = None` field to Transition
        # dataclass, and set it here: `transition.agent_id = getattr(self, 'agent_id', None)`

        # Store transition
        self.transitions.append(transition)

        return result

    return wrapper


# from tinker cookbook
@dataclass
class TrainingDatum:
    """A single training datum created from one or more transitions."""

    input_tokens: List[int]
    response_tokens: List[int]
    response_logprobs: Optional[List[float]]  # None when logprobs unavailable (e.g. external actions)
    response_mask: List[float]  # 0 for observation tokens, 1 for action tokens


def _is_prefix(sequence: List[int], candidate: List[int]) -> bool:
    """Check if sequence is a prefix of candidate."""
    if len(sequence) > len(candidate):
        return False
    return sequence == candidate[: len(sequence)]


def transitions_to_training_data(
    transitions: List[Transition],
) -> List[TrainingDatum]:
    """
    Convert a list of transitions into training data.

    If observations grow by appending (each successive observation contains
    the previous observation+action as a prefix), then we merge them into
    a single datum. Otherwise, we create separate data.

    For example, if ob_ac_pairs is:
    (O1, A1)
    (O1+A1+O2, A2)
    (O3, A3)

    We merge the first two into a single datum, and the last into a separate datum.

    Args:
        transitions: List of Transition objects

    Returns:
        List of TrainingDatum objects
    """

    if not transitions:
        return []

    data: List[TrainingDatum] = []

    full_sequence: List[int] = []
    sampled_logprobs: List[float] = []
    mask: List[float] = []
    has_valid_logprobs: bool = True

    def finalize_datum() -> Optional[TrainingDatum]:
        """Create a TrainingDatum from current accumulated state."""
        if not full_sequence:
            return None

        first_nonzero = mask.index(1) if 1 in mask else len(mask)
        if first_nonzero == len(mask):
            logger.warning("Datum has no action tokens (all mask is 0), skipping")
            return None

        input_tokens = full_sequence[:first_nonzero]
        response_tokens = full_sequence[first_nonzero:]
        response_mask = mask[first_nonzero:]

        if has_valid_logprobs:
            response_logprobs = sampled_logprobs[first_nonzero:]

            if len(response_logprobs) != len(response_tokens):
                logger.error(
                    f"response_logprobs length ({len(response_logprobs)}) "
                    f"!= response_tokens length ({len(response_tokens)})"
                )
                return None
        else:
            response_logprobs = None

        if len(response_mask) != len(response_tokens):
            logger.error(
                f"Length mismatch: response_mask ({len(response_mask)}) "
                f"!= response_tokens ({len(response_tokens)})"
            )
            return None

        return TrainingDatum(
            input_tokens=input_tokens,
            response_tokens=response_tokens,
            response_logprobs=response_logprobs,
            response_mask=response_mask,
        )

    def reset_accumulator():
        """Clear accumulator for next datum."""
        nonlocal full_sequence, sampled_logprobs, mask, has_valid_logprobs
        full_sequence = []
        sampled_logprobs = []
        mask = []
        has_valid_logprobs = True

    # Process each transition
    for idx, transition in enumerate(transitions):
        # Validation
        if transition.ob is None:
            logger.warning(f"Transition {idx} has None observation, skipping")
            continue
        if transition.ac is None:
            logger.warning(f"Transition {idx} has None action, skipping")
            continue

        ob_tokens = transition.ob.input_ids
        if not ob_tokens:
            logger.warning(f"Transition {idx} has empty observation tokens, skipping")
            continue

        ac_tokens = transition.ac.token_ids
        if not ac_tokens:
            logger.warning(f"Transition {idx} has empty action tokens, skipping")
            continue

        ac_logprobs = transition.ac.logprobs
        transition_has_valid_logprobs = (
            ac_logprobs is not None and len(ac_logprobs) == len(ac_tokens)
        )

        if not transition_has_valid_logprobs:
            if ac_logprobs is None:
                logger.debug(f"Transition {idx} has no logprobs")
            else:
                logger.warning(
                    f"Transition {idx} has mismatched logprobs "
                    f"({len(ac_logprobs)} logprobs vs {len(ac_tokens)} tokens)"
                )

        if len(full_sequence) == 0:
            # First transition always starts a new datum
            delta_ob_tokens = ob_tokens
        elif _is_prefix(full_sequence, ob_tokens):
            delta_ob_tokens = ob_tokens[len(full_sequence):]
        else:
            datum = finalize_datum()
            if datum:
                data.append(datum)
            reset_accumulator()
            delta_ob_tokens = ob_tokens

        if not transition_has_valid_logprobs and has_valid_logprobs:
            has_valid_logprobs = False

        # Accumulate tokens (pad logprobs with 0.0 when invalid — safe since has_valid_logprobs gates usage)
        full_sequence.extend(delta_ob_tokens)
        sampled_logprobs.extend([0.0] * len(delta_ob_tokens))
        mask.extend([0.0] * len(delta_ob_tokens))

        full_sequence.extend(ac_tokens)
        sampled_logprobs.extend(ac_logprobs if transition_has_valid_logprobs else [0.0] * len(ac_tokens))
        mask.extend([1.0] * len(ac_tokens))

    if full_sequence:
        datum = finalize_datum()
        if datum:
            data.append(datum)

    return data


# Custom exceptions for agent step control flow
class StepException(Exception):
    """Base exception for step control flow."""

    def __init__(self, step_result: StepResult):
        self.step_result = step_result
        super().__init__()


class ContextWindowExceeded(StepException):
    """Raised when context window is exceeded."""

    def __init__(self):
        super().__init__(StepResult.finished("CONTEXT_WINDOW_EXCEEDED", None))


class ParseError(StepException):
    """Raised when tool call parsing fails."""

    def __init__(self):
        super().__init__(StepResult.continuing(None))


class NoToolCall(StepException):
    """Raised when no tool call is detected."""

    def __init__(self):
        super().__init__(StepResult.continuing(None))


class ToolExecutionFailed(StepException):
    """Raised when tool execution fails."""

    def __init__(self):
        super().__init__(StepResult.continuing(None))
